### ISSUE TITLE
Bug: Custom .js files for templater are encrypted when received

### ISSUE THREAD

**Issue by kenjibailly** [vrtmrz/obsidian-livesync#43] opened 2022-01-26 05:47 UTC
Something goes wrong when receiving my custom .js files to use for templater. They are called "User Script Functions" in templater.
Templater completely breaks when the setting is active on the received scripts.

The cause is that my custom .js scripts are completely encrypted while not even using the encryption setting.

When I replace my received .js files with my local/server .js files the problem is gone as they are now not encrypted anymore.
This is a quick fix ofc, when I would receive my vault as new on a new pc, I'd have to copy over my scripts manually. 
I'm intending to share my vault with a bunch of people, so this becomes a problem.

**Comment by vrtmrz** [comment] 2022-01-27 03:20
Reproduced! 
It's a bug but not caused by encryption. 
The plugin thought it was the binary file when reading, and wrote the file as plain text,  
It has been fixed on v0.6.1.
Could you please try this?

**Comment by kenjibailly** [comment] 2022-01-27 05:23
Thank you so much for the quick support! It's working now!

**Closed** 2022-01-27 05:23 UTC
