### ISSUE TITLE
Data loss when adding a note through the "share" option on mobile (or when adding a note before the plugin fully initializes)

### ISSUE THREAD

**Issue by niieani** [vrtmrz/obsidian-livesync#122] opened 2022-09-27 23:00 UTC
Steps to reproduce:

1. device A: create a note "xyz"
1. device A: add content "`testing`"
1. device A: make sure the data is replicated to the backend
2. device B: make sure the data is replicated from the backend
3. device B: open the note "xyz", you should correctly see content "testing"
4. device B: close the app
5. device A: add more words to "xyz": "` - some change`"
6. device B: using another app, e.g. Instagram, use the Share link to Obsidian, and select "choose file to add to", choosing "xyz"
7. device B: the contents will now say: "`testing - https://instagram.com/...`"

What happens is that LiveSync will not try to resolve conflict here, and once it's synced it will just overwrite the file with the content from Device B. The new content from Device A ("` - some change`") is now lost.

This happened to me a few times, but thankfully I had been able to use the Snapshots feature to recover my notes. Now I started using Obsidian Git to just sync everything to git. But ideally I'd like LiveSync to present me with the "conflict resolution" box.

I think this happens because LiveSync plugin sometimes a long time to initialize on mobile devices (especially on Android, my iPad is much faster), so when you use the "Share" option the plugin is still initializing. LiveSync thinks the contents are newer (cause by date, they are), and it discards the content of the file from replication.

This also makes is impossible to use the "Open daily note on startup" feature of the built-in "Daily notes" plugin on more than one device, because it essentially will create a blank new file before the replication has started, so if you had the same file already create on another device, it would be overwritten. It would be great if there was logic to handle these cases.

**Comment by vrtmrz** [comment] 2022-09-28 01:55
Thank you for your question. I am also glad that you have clarified the behaviour of this case. Actually, I could not.

I had heard that a daily note had been erased before. But I could not reproduce it. However, its behaviour has become clear. This is so important reproducible procedure! I would like to really thank you once again.

If the files were added completely before Obsidian had been launched, or after stabilised boot sequence, it will be handled safely.
But if files have been changed while boot sequence, it cannot be handled as `Changed`. So LiveSync simply ignores this. Therefore, the content and timestamp of step 9 will not be recorded. As a result, LiveSync just accepts the changes or overwrites the older one. (Yes, this can happen both A or B). and history is not recorded because of this, it cannot be restored from the file history.

I will fix this soon.

**Comment by vrtmrz** [comment] 2022-09-28 09:37
@niieani 
Fixed in v0.15.7. Still a bit hypersensitive about file changes, but it works.
Could you please try this?

**Comment by niieani** [comment] 2022-09-29 09:10
Thank you for such a fast response and fix @vrtmrz! 
I will try it out. I'll do some testing, though since the problem was intermittent, I'll let you know if I still observe the issue in the future. If you don't hear back from me in a month in this thread you can consider it fixed. 🤞

**Comment by vrtmrz** [comment] 2022-10-03 02:11
@niieani 
I have changed the behaviour of this in v0.15.10, to avoid unexpected file detection on the boot sequence. But it could cause the mysterious behaviour again. (But the changes would be recorded into history and we can restore)

**Closed** 2023-04-12 08:41 UTC
