### ISSUE TITLE
constant error "bad_request:invalid UTF-8 JSON "

### ISSUE THREAD

**Issue by lovitus** [vrtmrz/obsidian-livesync#144] opened 2022-11-22 10:23 UTC
### after I pasted some picture to my note 
the sync suddenly don't work anymore 
after updated to the  latest  version of livesync plugin , error persistent.
any clue to  to debug it ?
```

11/22/2022, 6:18:13 PM->Retry with lower batch size:8/5
11/22/2022, 6:18:13 PM->Oneshot Sync begin... (sync)
11/22/2022, 6:18:14 PM->Replication activated
11/22/2022, 6:18:14 PM->Replication error
11/22/2022, 6:18:14 PM->bad_request:invalid UTF-8 JSON
11/22/2022, 6:18:14 PM->Replication stopped.
11/22/2022, 6:18:14 PM->Retry with lower batch size:6/5
11/22/2022, 6:18:14 PM->Oneshot Sync begin... (sync)
11/22/2022, 6:18:15 PM->Replication activated
11/22/2022, 6:18:15 PM->Replication error
11/22/2022, 6:18:15 PM->bad_request:invalid UTF-8 JSON
11/22/2022, 6:18:15 PM->Replication stopped.
11/22/2022, 6:18:15 PM->We can't replicate more lower value.
```

**Comment by lovitus** [comment] 2022-11-22 10:45
my picture only 500KB+

**Comment by lovitus** [comment] 2022-11-22 11:17
after changed
> chuck size from 0 to 1
> batch size  from 250 to 1024

still same

**Comment by lovitus** [comment] 2022-11-22 18:10
verbose &full log

```
11/23/2022, 2:08:55 AM->AbortError:The user aborted a request.
11/23/2022, 2:09:01 AM->Oneshot Sync begin... (sync)
11/23/2022, 2:09:02 AM->Replication activated
11/23/2022, 2:09:03 AM->Replication error
11/23/2022, 2:09:03 AM->bad_request:invalid UTF-8 JSON
11/23/2022, 2:09:03 AM->Replication stopped.
11/23/2022, 2:09:03 AM->Retry with lower batch size:127/22
11/23/2022, 2:09:03 AM->Oneshot Sync begin... (sync)
11/23/2022, 2:09:04 AM->Replication activated
11/23/2022, 2:09:05 AM->Replication error
11/23/2022, 2:09:05 AM->bad_request:invalid UTF-8 JSON
11/23/2022, 2:09:05 AM->Replication stopped.
11/23/2022, 2:09:05 AM->Retry with lower batch size:66/13
11/23/2022, 2:09:05 AM->Oneshot Sync begin... (sync)
11/23/2022, 2:09:06 AM->Replication activated
11/23/2022, 2:09:06 AM->Replication error
11/23/2022, 2:09:06 AM->bad_request:invalid UTF-8 JSON
11/23/2022, 2:09:06 AM->Replication stopped.
11/23/2022, 2:09:06 AM->Retry with lower batch size:35/9
11/23/2022, 2:09:06 AM->Oneshot Sync begin... (sync)
11/23/2022, 2:09:07 AM->Replication activated
11/23/2022, 2:09:08 AM->Replication error
11/23/2022, 2:09:08 AM->bad_request:invalid UTF-8 JSON
11/23/2022, 2:09:08 AM->Replication stopped.
11/23/2022, 2:09:08 AM->Retry with lower batch size:20/7
11/23/2022, 2:09:08 AM->Oneshot Sync begin... (sync)
11/23/2022, 2:09:09 AM->Replication activated
11/23/2022, 2:09:09 AM->Replication error
11/23/2022, 2:09:09 AM->bad_request:invalid UTF-8 JSON
11/23/2022, 2:09:09 AM->Replication stopped.
11/23/2022, 2:09:09 AM->Retry with lower batch size:12/6
11/23/2022, 2:09:09 AM->Oneshot Sync begin... (sync)
11/23/2022, 2:09:10 AM->Replication activated
11/23/2022, 2:09:10 AM->Replication error
11/23/2022, 2:09:10 AM->bad_request:invalid UTF-8 JSON
11/23/2022, 2:09:10 AM->Replication stopped.
11/23/2022, 2:09:10 AM->Retry with lower batch size:8/5
11/23/2022, 2:09:10 AM->Oneshot Sync begin... (sync)
11/23/2022, 2:09:11 AM->Replication activated
11/23/2022, 2:09:11 AM->Replication error
11/23/2022, 2:09:11 AM->bad_request:invalid UTF-8 JSON
11/23/2022, 2:09:11 AM->Replication stopped.
11/23/2022, 2:09:11 AM->Retry with lower batch size:6/5
11/23/2022, 2:09:11 AM->Oneshot Sync begin... (sync)
11/23/2022, 2:09:12 AM->Replication activated
11/23/2022, 2:09:13 AM->Replication error
11/23/2022, 2:09:13 AM->bad_request:invalid UTF-8 JSON
11/23/2022, 2:09:13 AM->Replication stopped.
11/23/2022, 2:09:13 AM->We can't replicate more lower value.
```

**Comment by vrtmrz** [comment] 2022-11-23 03:04
Thank you for using this plug-in and sending detailed information! 
They have been so helpful! May I ask you two or three more?

1. Could you please paste Obsidian debug information which can generate in `Show debug info` in the command palette? 
2. Could you please paste the reports you can generate in the hatch pane of the configuration dialogue? 
3. Would you check what does be shown in the network pane in the DevTools, please? Screen-shots are appreciated. I hope to see what error has been shown, so please capture them like [this](https://github.com/vrtmrz/obsidian-livesync/issues/134#issuecomment-1288098707). But please conceal your sensitive information.
 If you are troubled with iOS, it is not possible, so skip this step.
  
> chuck size from 0 to 1
> batch size from 250 to 1024

In this situation, the batch size should be reduced once. 50 or less is recommended in troubleshooting. The batch limit is also should be reduced to around 40 to 20 or less, but it cannot be so smaller.

If there are already chunks that are too large to be sent to the server even if the Batch Limit is minimised, changing the Chunk size now will not resolve the situation. In that case, We have to rebuild the database again.

**Comment by lovitus** [comment] 2022-11-23 03:50
show debug info 

```
SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v0.15.9
	Operating system: Windows 10 Pro N for Workstations 10.0.19044
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Big Sur Aesthetic
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 23
	Plugins enabled: 23
		1: Self-hosted LiveSync v0.16.6
		2: Quiet Outline v0.3.2
		3: Reminder v1.1.12
		4: Admonition v9.0.5
		5: Advanced Tables v0.17.3
		6: cMenu v1.1.2
		7: CodeMirror Options v0.9.5
		8: Contextual Typography v2.2.4
		9: Dataview v0.5.46
		10: Enhancing Mindmap v0.2.4
		11: Excalidraw v1.7.19
		12: Highlightr v1.2.2
		13: Kanban v1.3.17
		14: Linter v1.4.4
		15: Markdown prettifier v0.1.3
		16: Mind Map v1.1.0
		17: Natural Language Dates v0.6.1
		18: obsidian markmind v1.5.7
		19: Obsidian Tabs v1.0.7
		20: Outliner v3.0.0
		21: Tasks v1.13.1
		22: Timelines v0.3.2
		23: Pandoc Plugin v0.4.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

plugin generated report 
```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  require_valid_user: "true"
  secret: --masked-data--
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: false
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: true
periodicReplicationInterval: 60
syncOnFileOpen: false
encrypt: false
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
workingEncrypt: false
workingPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: false
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: true
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: true
checkIntegrityOnSave: false
batch_size: 250
batches_limit: 40
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: true
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: ""
ignoreVersionCheck: false
lastReadUpdates: 16
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 100
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
```

package capture in Devtools
Headers
```
Request URL: https://testcdn.***.us/obsidian/_bulk_docs
Request Method: POST
Status Code: 400
```
response
```
{"error":"bad_request","reason":"invalid UTF-8 JSON"}

```
head of the request

![image](https://user-images.githubusercontent.com/14361541/203465240-7c3c83ab-5b29-404f-aeae-5d9302e8e2ec.png)

mid of the request (some emojis)
![image](https://user-images.githubusercontent.com/14361541/203465317-e28a5e05-8b49-4727-b579-35c1da45f923.png)

the json format seems normal , and closed correctly at the end .

its just suddenly stopped work after I paste 4pictures from clipboard ( not sure its related, but the plugin did work always before that )
my couchdb instant is behind Cloudflare then Nginx, pretty sure those are configured correctly as well , I have wordpress and small media server in the same machine .

thanks again for investing into this , very appreciated .

**Comment by vrtmrz** [comment] 2022-11-23 06:19
Thank you for more details! 
I tested some cases, and unfortunately, I found that there seems to be no way to let it point to where was the invalid on the payload.
And I have also found that this error will be only raised when the JSON is really unacceptable.

As you suspected the emojis, I think so too. Or something UNICODE-ish things. 
Could you please set both the Batch limit and the batch size to 10 and try replication once? Then it might point us to an invalid chunk and we can investigate that more.

Or, if it could be run, that means some of the relays failed to transfer correctly.

I am sorry to ask you to go through all this trouble but thank you.

**Comment by lovitus** [comment] 2022-11-23 06:48
📌
🔋
#### 🔑
#### 💅
📖
##### 📚
📚
📒
#### 🖌
#### ⚙️
⬇️
###### 🤖
###### 📱
🛠
✅
🔸
⚠️
🔨
🟢

Ive changed the `batch limit ` and `batch size` to 10,
and replaced all emojis to empty string 

all  400 _buck_docs post json contents are contain   '📌' the pin icon
I guess that's the bug

anyway to drop history of only One piece of note for yesterday ? I'm too afraid to have to rebuild the remote database then I have to solve all my devices' sync.

or we could encode special characters and decode them  during sync process to avoid potential problem?

Thanks again and no need to say sorry , this plugin makes obsidian as my most important note taking tool.

**Comment by vrtmrz** [comment] 2022-11-23 08:55
> and replaced all emojis to empty string

> all 400 _buck_docs post json contents are contain '📌' the pin icon
> I guess that's the bug

Really thank you! I didn't reproduce it yet but would provide a clue. 
Perhaps I might ask you to share it with me if there are no confidential things in it. If you do not mind, please keep the payload to your local by `Copy object` on context-menu.

Chunks will not be deleted and not be skipped even if they are not in use at the time for several reasons. Once we made them, we have to transfer them to the remote once (if it is not there yet).
(When receiving, older and not conflicted revisions will be skipped, and unused chunks will be skipped by the feature of `Read chunks online`)
It makes us keep history, detect and resolve conflict, and keep storage and network usage low.
So even if you deleted emojis from the existing notes, replication should still be stalled due to the chunks.

Therefore, finally, we need to rebuild the database for efficiency. And this plug-in has been designed so. If we have the backup, it is not so dangerous.
Probably you knew but once we push `rebuild everything` on the most-correct device, all other devices will notice that they have to fetch a new database and notify us so. All that remains is to press `Fetch rebuilt DB`. 
It will not be resolved automatically and synching again. So we will not be going worse.
At that time, files are compared with their timestamp and overwritten, but we can roll them back because of revisions and undeleted chunks.

Or we can rebuild everything to another database to keep current one. (Only we have to do is suspend all synchronisation, copy the current configuration by `copy setup URI` once and jot it, change the database name directly on the remote database pane, push `Rebuild everything`, copy setup URI and open them on the other devices. )

> Thanks again and no need to say sorry , this plugin makes obsidian as my most important note taking tool.

Thanks for the kind words! I'd like to say thank you too.

**Comment by vrtmrz** [comment] 2022-11-23 13:15
Thank you for sharing! I'll check it later!

> I did rebuild everything and Fetch rebuilt DB on my two most used devices, works perfectly 🙌🌼

Awesome! And I am really relieved to hear that! 

 > but could I ignore the Warning in Hatch? I have more than 30 devices, I only want to "make as solved/ Fetch rebuilt DB" when I really use them 

Yes. In this case, leaving it be warned is preferred. 
If unlocking this is,  all subsequent devices will not be able to detect the remote database had been rebuilt. And they will start merging their databases. It should be a sort of nightmare.

**Comment by vrtmrz** [comment] 2022-11-24 00:58
Still a work in progress, but I found out why and what it is `invalid`.
All each emojis were innocent! Due to splitting them inside characters while making chunks, had turned into an **invalid UTF-8**. 
And it would not happen while enabling end-to-end encryption. Since the circumstances are limited, It had been so hard to reproduce. 

If I do not have the payload which you shared, it would have been a cold case. I'd love to thank you once again!

It will be fixed soon!

**Comment by lovitus** [comment] 2022-11-24 01:34
Bravo 👏👏👏!
Your posts were too much polite ,you should've asked me directly for `the payload  after changing Chunk size and limit`,that could save your time for other meaningful things .
Very impressed by your fast responses and ready to fix it

**Comment by vrtmrz** [comment] 2022-11-24 08:43
Thank you very much! I have been not familiar with English outside of work writing, so it can be a bit stuffy. I'll try to be just right!
(And, perhaps we need an issue template)

The fixed new version has been released! You already resolved the problem through workarounds, but would not happen again with your contribution! Cheers!

P.S. Also thank you for sponsoring!

**Closed** 2022-11-25 02:26 UTC
