### ISSUE TITLE
Reduce the same messages on popup notifications

### ISSUE THREAD

**Issue by thehotery** [vrtmrz/obsidian-livesync#23] opened 2021-12-02 13:26 UTC
All on screenshot
![image](https://user-images.githubusercontent.com/62539068/144430222-fb6c46c2-3fe7-4455-a39c-eb75901861a1.png)

_btw, if possible, increase the display time of messages, sometimes messages are quite large and difficult to read_

**Comment by vrtmrz** [comment] 2021-12-02 23:40
This message is caused by using different passphrases in the end-to-end encryption.

As you say, it will show a lot of messages.
This is the harassment to gain the time from casual-attackers.
But I thought, perhaps the real attacker will make the decrypting program instead of using Obsidian and this plugin. 

If increase the closing timeout, notifications would be obstacles to using obsidian, so may I reuse notify dialog that is like replication progress?

**Comment by vrtmrz** [comment] 2021-12-11 08:22
I completely forgot to notify you, it should be a little better since 0.1.23.

If you feel something, please open this issue again.

**Closed by vrtmrz** 2021-12-11 08:22 UTC
