### ISSUE TITLE
 "TypeError: Load failed" and "Could not connect to server" error on iOS

### ISSUE THREAD

**Issue by SONDLecT** [vrtmrz/obsidian-livesync#75] opened 2022-05-09 17:20 UTC
Cheers, thank you for this plugin! It looks to be exactly what I'm looking for and it's *so close* to working, but I'm running into troubles syncing to an iOS device.

I have a couchdb database hosted and behind a reverse proxy and accessible from the web and appears to be configured and working on a desktop instance of Obsidian. By using the couchdb/_utils tool I can confirm the database has been created and thee desktop Obisidian instance has uploaded information to that database. However, when I try to sync on an iOS device, after using the same login information, encryption passphrase, and database name, I get an error that says it cannot connect to the server, that "TypeError: Load failed". If I'm in the settings in the LiveSync plugin I can click "test connection" and it will appear to work, saying that it has connected to the correct database. I have no idea why iOS is throwing up the TypeError load fail error. From what I understand iOS is purposefully vague with those kinds of errors - but I can confirm the username and password and encryption passphrase are correct.

I've no real idea where to go from here, I feel like I've tried and confirmed all the credentials, and the test in the settings seems to work fine. It *almost* looks like the app is trying to use the old version of syncing, a feature that *says* is locked to mobile devices in the settings, but that can be toggled on and off. When toggled off, the test connects successfully, but when I toggle it on I get the same TypeError: Load Failed error.

My desktop instance is running on windows. The database is a couchdb docker container, properly exposed. The iOS device is updated to the most recent version of iOS. Am I doing something blindingly stupid and just missing something obvious? (I'd paste the sync status logs here but for some reason I can't copy them out of the iOS app..)

**Comment by PTiedt** [comment] 2022-05-09 21:41
Same thing here: couchdb on docker behind proper configured reverse proxy, a working windows app. In my scenario the couchdb is just exposed internally. (DNS isn't a problem, already checked that)

On iOS when i turn off "old connecting method" it replies "connected to", if i try to replicate data it says 
> could not connect to https://[url]/couchdb: TypeError:Load failed
> Could not connect to server.

If i check "Use the old connecting method" the error is shown for "Test Database Connection" aswell.
Windows app is fine ("new" connection method).

**Comment by vrtmrz** [comment] 2022-05-10 07:37
Thank you for asking me!
It looks like the CORS. 
This problem had been avoided by the new connecting method once. But as like in #63, we can't use the new connecting method on mobile. So it has been reverted.

I made a new feature `Check database configuration` on v0.9.0 to investigate the cause of the problem. Might not be a problem, but could you try it once?

Also, if there are no problems, I'll create an option "Use new connection method for except LiveSync".

**Comment by SONDLecT** [comment] 2022-05-10 10:01
> Thank you for asking me! It looks like the CORS. This problem had been avoided by the new connecting method once. But as like in #63, we can't use the new connecting method on mobile. So it has been reverted.
> 
> I made a new feature `Check database configuration` on v0.9.0 to investigate the cause of the problem. Might not be a problem, but could you try it once?
> 
> Also, if there are no problems, I'll create an option "Use new connection method for except LiveSync".

I'll be more than happy to try anything! How can i use the  `check database configuration`  feature?  I'm not seeing it in the options.

**Comment by PTiedt** [comment] 2022-05-10 10:12
> Thank you for asking me! It looks like the CORS. This problem had been avoided by the new connecting method once. But as like in #63, we can't use the new connecting method on mobile. So it has been reverted.
> 
> I made a new feature `Check database configuration` on v0.9.0 to investigate the cause of the problem. Might not be a problem, but could you try it once?
> 
> Also, if there are no problems, I'll create an option "Use new connection method for except LiveSync".

worked for me. updated plugin, did check database and had several things to fix. afterwards the iOS app replicated successfully - livesync feature works as intended.

thank you for the fast fix :)

**Comment by vrtmrz** [comment] 2022-05-11 09:53
I'm very glad to hear that you could synchronize with the remote database!

@SONDLecT 
> There was some confusion about the remote database getting locked and needing to mark device as resolved - I think the error messages there could be a bit clearer - but this is incredible! Thank you so much!

You right. Poor documentation and message is the problem to solve.  These items are written in the early days, so in bad and terribly complicated English. Day by day, my English is getting better thanks to you all. So, I think, documentation will be improved step by step (If other problems are not there.)
If you have some ideas to improve messages, feel free to make an issue and/or the pull request!

>A quick question: I'm hoping to use this to finally organize a massive folder of DND PDFs and notes. If the PDFs alone number in say 200gb, how large should I expect the database to be? 

It uses about 33% extra to save binary files. And encryption also uses about 50% extra. So totally about 200% or a bit less. (Of course, your storage won't be spent as is, Obsidian compress them internally)
But if there are some same files or same part of files, it will be deduplicated. If you have old and new PDFs which updated with incremental updates, you can save the database usage and replication time.

**Comment by vrtmrz** [comment] 2022-09-12 02:56
Close this issue once. Feel free to open it again if you have new something.

**Closed by vrtmrz** 2022-09-12 02:56 UTC
