### ISSUE TITLE
fonts file sync error

### ISSUE THREAD

**Issue by wangweitung** [vrtmrz/obsidian-livesync#280] opened 2023-09-08 04:06 UTC
## Abstract
fonts file sync error

## Actually happened
- put any fonts file in the vault,on the pc ,it 5Mb,after syncing to the phone it becomes 33Mb.
- my test font file name【字语青梅硬笔.ttf】

original file size：
![图片](https://github.com/vrtmrz/obsidian-livesync/assets/8080125/82f34d4a-763d-4bad-9c62-8e376c1791b6)

after syncing on mobile :

![图片](https://github.com/vrtmrz/obsidian-livesync/assets/8080125/35a1ea9e-4832-4991-b232-27b0f1f41ae5)

**Comment by vrtmrz** [comment] 2023-09-15 01:16
Thank you for opening the issue! 
However, I regret to say this but I could not reproduce it.

May I have some questions?

- Could you see the head of the transferred font file? We can open it and change the extension to `.md` to see the content in force. If it begins with...
  - `AAEA...`: This means stored as binary but restored as plain text. 
  - `["...`: This means stored with end-to-end encryption, but restored without it.
  - Something binary-ish: In this case, it is a failed save or merge.

I hope to fix the issues and make all of us happy. I am sorry to bother you, but I would appreciate it if you could check and let me know.

**Comment by wangweitung** [comment] 2023-09-15 02:19
> Thank you for opening the issue! However, I regret to say this but I could not reproduce it.
> 
> May I have some questions?
> 
> * Could you see the head of the transferred font file? We can open it and change the extension to `.md` to see the content in force. If it begins with...
>   
>   * `AAEA...`: This means stored as binary but restored as plain text.
>   * `["...`: This means stored with end-to-end encryption, but restored without it.
>   * Something binary-ish: In this case, it is a failed save or merge.
> 
> I hope to fix the issues and make all of us happy. I am sorry to bother you, but I would appreciate it if you could check and let me know.


>Could you see the head of the transferred font file? 

none of you have listed. this is the download link.    .ttf is the font file

https://dwangdun.jb51.net/font/2020/ziyuqmyb_jb51.rar

**Closed** 2023-09-22 02:42 UTC
