### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by superyuuki** [vrtmrz/obsidian-livesync#54] opened 2022-04-07 02:01 UTC
I put in all my db details but the sync icon always shows stopped

**Comment by superyuuki** [comment] 2022-04-07 02:03
Update: Closing and re opening gives error 

```
4/6/2022, 7:02:43 PM->loading plugin
4/6/2022, 7:02:43 PM->Open Database...
4/6/2022, 7:02:43 PM->Database Info
4/6/2022, 7:02:43 PM->Database is now ready.
4/6/2022, 7:02:43 PM->Database closed (by close)
4/6/2022, 7:02:43 PM->Open Database...
4/6/2022, 7:02:43 PM->Database Info
4/6/2022, 7:02:43 PM->Database is now ready.
4/6/2022, 7:02:43 PM->Initialize and checking database files
4/6/2022, 7:02:43 PM->Updating database by new files
4/6/2022, 7:02:43 PM->UPDATE DATABASE
4/6/2022, 7:02:43 PM->UPDATE STORAGE
4/6/2022, 7:02:43 PM->CHECK FILE STATUS
4/6/2022, 7:02:43 PM->Initialized,NOW TRACKING!
4/6/2022, 7:02:43 PM->Replication closed
4/6/2022, 7:02:44 PM->Error:Request Error:404
4/6/2022, 7:02:44 PM->Error while loading Self-hosted LiveSync
```

**Comment by superyuuki** [comment] 2022-04-07 02:08
```
4/6/2022, 7:07:24 PM->Database is now ready.
4/6/2022, 7:07:24 PM->Database closed (by close)
4/6/2022, 7:07:24 PM->Open Database...
4/6/2022, 7:07:24 PM->Database Info
4/6/2022, 7:07:24 PM->{
  "doc_count": 5,
  "update_seq": 10,
  "idb_attachment_format": "binary",
  "db_name": "matt-livesync",
  "auto_compaction": true,
  "adapter": "idb"
}
4/6/2022, 7:07:24 PM->Database is now ready.
4/6/2022, 7:07:24 PM->Initialize and checking database files
4/6/2022, 7:07:24 PM->Updating database by new files
4/6/2022, 7:07:24 PM->UPDATE DATABASE
4/6/2022, 7:07:24 PM->UPDATE STORAGE
4/6/2022, 7:07:24 PM->CHECK FILE STATUS
4/6/2022, 7:07:24 PM->Initialized,NOW TRACKING!
4/6/2022, 7:07:24 PM->Replication closed
4/6/2022, 7:07:24 PM->HTTP:GET to:/ -> 200
4/6/2022, 7:07:24 PM->HTTP:GET to:/ -> 200
4/6/2022, 7:07:24 PM->HTTP:GET to:/obsydian_livesync_version? -> failed
4/6/2022, 7:07:24 PM->Error:Request Error:404
4/6/2022, 7:07:24 PM->Error while loading Self-hosted LiveSync
4/6/2022, 7:07:24 PM->Error:Request Error:404
```

**Comment by Limezy** [comment] 2022-04-07 04:47
I have exactly the same error

**Comment by vrtmrz** [comment] 2022-04-07 07:24
@Limezy @superyuuki 
Thanks for reaching out to me!
It's caused by the new API and first synchronization.
I fixed this on v0.8.2. Could you please try this?

**Comment by Limezy** [comment] 2022-04-07 08:37
Wow that was a quick fix !
Now syncing my 20k files database without any issues 👍

**Comment by superyuuki** [comment] 2022-04-08 04:05
Hey, incredible work patching that so fast ;) Can confirm it does work again!

**Comment by vrtmrz** [comment] 2022-07-20 15:58
Close this issue once. Feel free to make a new issue. Thank you!

**Closed by vrtmrz** 2022-07-20 15:58 UTC
