### ISSUE TITLE
LiveSync does not down load files from DB, when the file name contain ‘“‘

### ISSUE THREAD

**Issue by muuky** [vrtmrz/obsidian-livesync#173] opened 2023-02-11 00:52 UTC
I am Using LiveSync with three multiple devices
- Mac Mini, Ipad, IPhone

I found some missing files when I open Obsidian from mobile.

![이미지 2023  2  11  오전 9 39](https://user-images.githubusercontent.com/34735152/218227305-33b847cf-751a-4ced-a47e-872344f1b4af.jpeg)

this is my MacMini’s log, as you can see,  my MacMini Successfully update DB with “test”.md
> 2023. 2. 11 09:24:29 -> UPDATE DATABASE “test”.md

But, on all my mobile devices, LiveSync CAN NOT Download “test”.md

i have over 400 Markdown files which contains ‘“‘
All of them missing on mobile.

**Comment by vrtmrz** [comment] 2023-02-13 01:08
Thank you for opening this issue!

This is an intended behaviour. However, as in this case, it can be a useless restriction. Windows devices will not be able to create files named like this, so it has been prevented.

To improve this, we should address the detection of the platform when checking if the path is valid. 

It will be fixed.

**Comment by vrtmrz** [comment] 2023-02-15 03:39
@muuky 
Sorry for the delayed response! Fixed at v0.17.23!
Could you please try this version?

**Closed** 2023-05-25 13:37 UTC
