### ISSUE TITLE
Duplicate file after moving to new directory 

### ISSUE THREAD

**Issue by Vyeche** [vrtmrz/obsidian-livesync#133] opened 2022-10-20 17:44 UTC
I noticed after I move files into another directory, it creates a duplicate. I've seen it between different devices connected to the same Vault. I don't have any logs to show it yet.

**Comment by vrtmrz** [comment] 2022-10-25 07:41
Sorry for being late! but I could not reproduce it.
Have you noticed any condition or reproducing procedure?

**Comment by vrtmrz** [comment] 2022-10-27 09:21
Thank you for the detail! I did not reproduce this exactly but yesterday I began to be also troubled by a similar case.

And finally I found that there are some deleted notes that had been conflicted. After resolving them, my machines could synchronise all of them.

I implemented a feature that can resolve the conflict of the deleted notes in v0.16.5. 
We can select the conflicted file by `Pick a file to resolve conflict` from the Command palette. If there are no conflicted documents, the message will be shown so.
Could you please try this once?

**Comment by Vyeche** [comment] 2022-10-27 21:45
Wow, great idea; I have so many of them!?

![image](https://user-images.githubusercontent.com/972377/198404239-24554330-5870-47b8-bf0f-f97b66c7de25.png)

**Comment by vrtmrz** [comment] 2022-10-28 10:37
When I first read your reply in my email notification, I thought I had suggested an atrocious approach. A terribly troublesome solution.
But I came here and saw your edit, and I was really relieved.

Yes, automatically merging is the correct behaviour. Regular files had already been done. In my case, I had to resolve them.

I hope this can solve the duplication of deleted files.

**Comment by Vyeche** [comment] 2022-10-28 16:16
Yeah I love the new way. I spent the evening resolving a ton of them. Thank you for the method. 

I noticed a new feature to delete meta data for deleted files. These conflicts are related to that right? 

I noticed that Obsidian does this reindex thing that might touch a bunch of files. I'm monitoring if it creates conflicts.

**Closed** 2023-02-28 22:24 UTC
