### ISSUE TITLE
Memory Leak Report.

### ISSUE THREAD

**Issue by justemu** [vrtmrz/obsidian-livesync#76] opened 2022-05-13 16:16 UTC
First this is an amazing plugin. While it seems that there is a memory leakage.

To reproduce:
- setup the plugin. turn on live sync preset.
- The status bar keeps showing update database...
- Serveral minutes later, obsidian turns black and stops reponse. even `ctrl+shift+i` could not open console for error information check. 

- restart obsidian. and serveral minutes later. the obsidian turns black again...

- restart obsidian again, and turn off this plugin. there is no more black screens.

- turn on the plugin again and open windows taskmanager to monitor obsidian... and I found the obsidian kept 30-50% usage of CPU , while the memory usage keeps climbing... until it reached 3-4 gigabyte and crashed. That is the very time that obsidian turned black.. It is very obvious that when this plugin in the process of "update database " caused some kind of memory leakage and burst.

**Comment by vrtmrz** [comment] 2022-05-16 11:44
Thank you for making this issue!
But I couldn't reproduce this... How many files do you have? And may I ask the total size of them?
If you open DevTools in advance, do you get something?

**Comment by justemu** [comment] 2022-05-18 02:49
I kept the DevTools open.. 
The log in the console stopped at “Vaultname: 2022/5/18 10:31:57 -> Connected to ob”
No any kind of error infomation. And the memory usage start climbing... until 6 gigabytes and burst.
I captured the screen in sequence... 
![image](https://user-images.githubusercontent.com/20639347/168945431-7cfae5a3-626a-42ab-933a-79abf01906f9.png)
![image](https://user-images.githubusercontent.com/20639347/168945441-dcd12363-0049-4494-baa8-fc79967f1125.png)
![image](https://user-images.githubusercontent.com/20639347/168945453-3c0a615a-d466-4b22-90bb-b579a0c8c05b.png)
![image](https://user-images.githubusercontent.com/20639347/168945543-bd8c06b4-49ff-4c00-9b0a-775d7159aebc.png)
After burst, memory usage return to regular level... That is 800mb in my case (with 43 plugins in my vault).
The total size of my vault folder is  191MB (2345 files) including 43 plugins. It not a big vault.

**Comment by vrtmrz** [comment] 2022-06-10 23:55
@justemu 
I made an investigation in deep, but couldn't make sure exactly the reason. But looks like there were multiple possibilities. 
So I rewrite the algorithm for saving chunks and replicating them.

As a side benefit, it increased speed, and the code is now tidied up! 

Could you please test whether new behavior is appropriate for your vault too?

**Comment by vrtmrz** [comment] 2022-07-20 16:05
Since March, many updates are released and bugs are fixed. So, Close this issue once. Feel free to make a new issue. Thank you!

**Closed by vrtmrz** 2022-07-20 16:05 UTC
