### ISSUE TITLE
ibm over fly.io: an observation

### ISSUE THREAD

**Issue by kzssc** [vrtmrz/obsidian-livesync#453] opened 2024-06-14 11:36 UTC
fly.io might be conducive to conflicting database config (or the inability to implement the config in full) across different platforms. For me, the conflict emerges as soon as I incorporate a windows machine into my ios+macos+android bunch. A pop-up indicating inconsistent config will emerge and prevent syncing, unless i choose the config which is local to the windows environment  - not the server config generated by my other machines) can the synching be resumed. This, however, will prompt the same pop-up with my other machines, thus preventing a uninterrupted sync (in this case, however, i can choose whatever config i prefer - this can resume the sync. If the config chosen here is different to the windows machine, windows will resume pop-up). 

## Expected behaviour
No clash in config. 

## Actually happened
inconsistent config on windows machines. 

## Report materials
Since I've moved to the IBM Cloudant system, this problem has went away. I thus cannot produce a diagnosis report.

**Comment by vrtmrz** [comment] 2024-07-02 06:56
Thank you for asking me!
I think that this is the same as #446, caused by a complicated dialogue message. Moving to IBM Cloudant might have made the configuration unified as a side effect.

I will improve the message or behaviour of the unifying configuration.
If you have some other notices, please feel free to open this issue again!

**Closed by vrtmrz** 2024-07-02 06:56 UTC
