### ISSUE TITLE
plugin started to corrupt data in 0.23.12

### ISSUE THREAD

**Issue by raven428** [vrtmrz/obsidian-livesync#447] opened 2024-06-03 08:40 UTC
## Abstract
Version 0.23.12 started to corrupt data for sync where 0.23.11 was fine

## Expected behaviour
Full note sync

## Actually happened
If a note contain lines bellow:
````md
# test header
```
test code block
```
````
Without any separating data between line `# test header` and line ` ``` ` then plugin put to CouchDB the note truncated after `# test header` line

In this case note will be synchorized to CouchDB completely:
````md
# test header
some data separate
header and code lines
```
test code block
```
````

## Reproducing procedure
1. Install version 0.23.12 with default configuration
2. Configure sync to CouchDB
3. Put the text reported above to note
4. Click the replication button on the ribbon.
5. Sync will put only the truncated note to CouchDB

The same procedure will be fine in 0.23.11, which I'll still use. Tried at Obsidian version 1.5.12 for Windows and Android - both affected

**Comment by vrtmrz** [comment] 2024-06-04 10:43
Thank you for reporting this! I completely have not noticed this!
And, thanks to your detailed report, I could fix that quickly!
This has been fixed at v0.23.13. Would you mind if I ask you to check the behaviour, please?

**Comment by foegra** [comment] 2024-06-04 11:20
I have had the same issue. 
I really like the plugin, but while I was using it - synchronization has gone bananas couple of times. 

Perhaps it would be wise to introduce beta release branch to keep the main release branch as stable as possible?

**Comment by vrtmrz** [comment] 2024-06-04 11:35
Thank you for using Self-hosted LiveSync!
I think your problems and their solutions are reasonable.
However, this bug could actually be avoided by disabling the new default feature.
Therefore, a beta release would have been good, but a case like this would have been done anyway.

So, probably not what you want again, but new feature will be released not as a beta release but a as a beta configuration. And I will disable the new feature in default.
(Instead, a dialogue will ask us if we want to enable it or not, when a new feature have added or, when after n versions have passed since the new feature was added).

**Comment by raven428** [comment] 2024-06-04 13:01
Could you please share what new feature you mentioned? Just curious

**Comment by vrtmrz** [comment] 2024-06-04 13:09
@raven428  Thank you for asking! This has been caused by splitting chunks in background. While passing split strings to foreground, empty string had been detected as End-of-strings, unfortunately.  (We had been able to disable it in the Hatch pane).

**Comment by Opisek** [comment] 2024-06-06 08:18
Same issue. I was horrified to see all my notes becoming empty, as they all start with a [table of contents](https://github.com/johansatge/obsidian-automatic-table-of-contents/issues).
```
# Table of Contents
\```table-of-contents
\```
```

When can we expect a hotfix. This can cause serious corruption.

**Comment by Opisek** [comment] 2024-06-06 09:00
Seems to be resolved by the newest release. Can the issue be closed?

**Comment by vrtmrz** [comment] 2024-07-02 06:12
Thank you for your confirmation! (and sorry for being delayed).

**Closed** 2024-07-02 06:14 UTC
